services:

  db:
    container_name: greenlight-db
    image: postgres:16.3-alpine3.20
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=greenlight-admin
      - POSTGRES_DB=greenlight-db
    networks:
      - greenlight-network




networks:
  greenlight-network:
    driver: bridge